enum MenuIcon {
  dashboard = 'dashboard',
  sales = 'sales',
  inventory = 'inventory',
  customers = 'customers',
  suppliers = 'suppliers',
  products = 'products',
  invoices = 'invoices',
  contracts = 'contracts',
  payments = 'payments',
  cashRegister = 'cashRegister',
  savings = 'savings',
  accounts = 'accounts',
  audit = 'audit',
  reports = 'reports',
  fiscalPolicies = 'fiscalPolicies',
  taxReturn = 'taxReturn',
  logistics = 'logistics',
  company = 'company',
  compliance = 'compliance',
  notifications = 'notifications',
  userManagement = 'userManagement',
  receipts = 'receipts',
  transactions = 'transactions',
  bank = 'bank',
  taxManagement = 'taxManagement',
  warehouse = 'warehouse',
  budgets = 'budgets',
  store = 'store',
  priceTags = 'priceTags',
  schedule = 'schedule',
  reportsOverview = 'reportsOverview',
  tasks = 'tasks',
  searchFinance = 'searchFinance',
  events = 'events',
  policy = 'policy',
  legal = 'legal',
  orders = 'orders',
  tags = 'tags',
  user = 'user',
  settings = 'settings',
}
const menuData = [
  {
    Icon: MenuIcon.dashboard,
    name: 'tableau de bord',
    path: '/',
    actions: [],
  },
  {
    Icon: MenuIcon.settings,
    name: 'settings',
    actions: [
      {
        Icon: null,
        name: 'Menus',
        path: '/list/core/menu',
        actions: [],
      },
      {
        Icon: null,
        name: 'permissions',
        path: '/list/core/action',
        actions: [],
      },
      {
        Icon: null,
        name: 'roles',
        path: '/list/core/role',
        actions: [],
      },
      {
        Icon: null,
        name: 'utilisateurs',
        path: '/list/core/user',
        actions: [],
      },
    ],
  },
  {
    Icon: MenuIcon.user,
    name: 'profile',
    actions: [
      {
        Icon: null,
        name: 'change le mot de passe',
        path: '/change/auth/password',
        actions: [],
      },
      {
        Icon: null,
        name: 'se deconnecter',
        path: '/auth/login',
        actions: [],
      },
    ],
  },
];
